apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backup-deploy
  minReadySeconds: 5
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 1
    maxUnavailable: 2
  template:
    metadata:
      labels:
        app: backup-deploy
    spec:
      containers:
      - name: backup-container
        image: nikkoworld/nodebuild:2.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9700
        livenessProbe:
         httpGet:
          path: /home
          port: 9700
         initialDelaySeconds: 5
         periodSeconds: 5
        readinessProbe:
         httpGet:
          path: /home
          port: 9700
         initialDelaySeconds: 5
         periodSeconds: 5
  revisionHistoryLimit: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: backup-deploy
  type: LoadBalancer
  ports:
  - port: 9701
    targetPort: 9700
